library(tidyverse)
data = read_tsv("graph.tsv")
view(data)
data = read_tsv("graph.tsv")
view(data)
data %>% select(host) %>%
group_by(host)
data %>% select(host) %>% group_by(host) %>% summarise(n=n())
data %>% filter(host="w-galaxy") %>% select(cwd) %>% group_by(cwd) %>% summarize(n=n())
data %>% filter(host=="w-galaxy") %>% select(cwd) %>% group_by(cwd) %>% summarize(n=n())
data %>% filter(host=="w-galaxy") %>% select(cwd) %>% group_by(cwd) %>% summarize(n=n()) %>% arrange(-n)
data %>% filter(cwd=/arbeit/) %>% select(cwd) %>% group_by(cwd) %>% summarize(n=n()) %>% arrange(-n)
data %>% filter('arbeit' in cwd)
data %>% filter(grep("arbeit", cwd))
data %>% filter(grepl("arbeit", cwd))
data %>% filter(grepl("arbeit", cwd)) %>% select(cwd) %>% group_by(cwd) %>% summarize(n=n()) %>% arrange(-n)
data %>% filter(grepl("arbeit", cwd)) %>% select(cwd) %>% mutate(cwd2=gsub('hxr', 'user', cwd) %>% group_by(cwd2) %>% summarize(n=n()) %>% arrange(-n)
)
data %>% filter(grepl("arbeit", cwd)) %>% select(cwd) %>% mutate(cwd2=gsub('hxr', 'user', cwd)) %>% group_by(cwd2) %>% summarize(n=n()) %>% arrange(-n)
data %>% select(date, host) %>% ggplot(aes(x=date,y=host)) + geom_histogram()
data %>% select(date, host) %>% ggplot(aes(x=date)) + geom_histogram()
data %>% select(date, host) %>% ggplot(aes(x=date, fill=host)) + geom_histogram()
library(tidyverse)
data = read_tsv("issues.tsv")
data = read_tsv("issues.tsv")
data %>% mutate(week=strftime(date, "%Y-%W"))
data %>% mutate(week=strftime(date, "%Y-%W"))
data %>% mutate(week=strftime(date, "%Y-%W"))$week
data %>% mutate(week=strftime(date, "%Y-%W")) %>% select(week)
data %>% mutate(week=strftime(date, "%Y-%W")) %>% group_by(week) %>% summarise(n=n())
data %>% mutate(week=strftime(date, "%Y-%W")) %>% group_by(week) %>% summarise(n=n()) %>% ggplot2()
data %>% mutate(week=strftime(date, "%Y-%W")) %>% group_by(week) %>% summarise(n=n())
data %>% mutate(week=strftime(date, "%Y-%W")) %>% group_by(week, org) %>% summarise(n=n())
data %>% mutate(week=strftime(date, "%Y-%W")) %>% group_by(week, org) %>% summarise(n=n()) %>% ggplot2(aes(x=week, y=n, fill=org))
data %>% mutate(week=strftime(date, "%Y-%W")) %>% group_by(week, org) %>% summarise(n=n()) %>% ggplot(aes(x=week, y=n, fill=org)) + geom_col()
data %>% group_by(org) %>% summarize(n=n())
data %>% group_by(org) %>% summarize(n=n()) %>% arrange(n)
data %>% group_by(org) %>% summarize(n=n()) %>% arrange(n) %>% filter(n>1)
data %>% group_by(org) %>% summarize(n=n()) %>% arrange(n) %>% filter(n>2)
most = data %>% group_by(org) %>% summarize(n=n()) %>% arrange(n) %>% filter(n>2)
data %>% filter(org %in% most$org)
data %>% filter(org %in% most$org) %>% mutate(week=strftime(date, "%Y-%W")) %>% group_by(week, org) %>% summarise(n=n()) %>% ggplot(aes(x=week, y=n, fill=org)) + geom_col()
data %>% filter(org %in% most$org) %>% mutate(week=strftime(date, "%Y-%m")) %>% group_by(week, org) %>% summarise(n=n()) %>% ggplot(aes(x=week, y=n, fill=org)) + geom_col()
data %>% filter(org %in% most$org) %>% mutate(week=strftime(date, "%Y-%m")) %>% group_by(week, org) %>% summarise(n=n()) %>% ggplot(aes(x=week, y=n, fill=org)) + geom_col() + theme(axis.text.x = element_text)
data %>% filter(org %in% most$org) %>% mutate(week=strftime(date, "%Y-%m")) %>% group_by(week, org) %>% summarise(n=n()) %>% ggplot(aes(x=week, y=n, fill=org)) + geom_col() + theme(axis.text.x = element_text(angle=90))
data %>% filter(org %in% most$org) %>% mutate(week=strftime(date, "%Y-%m")) %>% group_by(week, org) %>% summarise(n=n()) %>% ggplot(aes(x=n, y=week, fill=org)) + geom_col() + theme(axis.text.x = element_text)
data %>% filter(org %in% most$org) %>% mutate(week=strftime(date, "%Y-%m")) %>% group_by(week, org) %>% summarise(n=n()) %>% ggplot(aes(x=n, y=week, fill=org)) + geom_bar() + theme(axis.text.x = element_text)
data %>% filter(org %in% most$org) %>% mutate(week=strftime(date, "%Y-%m")) %>% group_by(week, org) %>% summarise(n=n()) %>% ggplot(aes(x=week, y=n, fill=org)) + geom_col() + theme(axis.text.x = element_text(angle=90))
data %>% filter(org %in% most$org) %>% mutate(week=strftime(date, "%Y-%m")) %>% group_by(week, org) %>% summarise(n=n()) %>% ggplot(aes(x=week, y=n, fill=org)) + geom_col() + theme(axis.text.x = element_text(angle=90)) + ylab("Count") + ggtitle(Issues filed by hexylena per month"")
data %>% filter(org %in% most$org) %>% mutate(week=strftime(date, "%Y-%m")) %>% group_by(week, org) %>% summarise(n=n()) %>% ggplot(aes(x=week, y=n, fill=org)) + geom_col() + theme(axis.text.x = element_text(angle=90)) + ylab("Count") + ggtitle(Issues filed by hexylena per month")
data %>% filter(org %in% most$org) %>% mutate(week=strftime(date, "%Y-%m")) %>% group_by(week, org) %>% summarise(n=n()) %>% ggplot(aes(x=week, y=n, fill=org)) + geom_col() + theme(axis.text.x = element_text(angle=90)) + ylab("Count") + ggtitle("Issues filed by hexylena per month")
data %>% filter(org %in% most$org) %>% mutate(week=strftime(date, "%Y-%m")) %>% group_by(week, org) %>% summarise(n=n()) %>% summary()
ggsave("hexyissues.png")
data %>% filter(org %in% most$org) %>% mutate(week=strftime(date, "%Y-%m")) %>% group_by(week, org) %>% summarise(n=n()) -> tmp
tmp
tmp$n
sd(tmp$n)
data%>% mutate(week=strftime(date, "%Y-%m")) %>% group_by(week, org) %>% summarise(n=n()) -> tmp
sd(tmp$n)
summary(tmp$n)
tmp
data%>% mutate(week=strftime(date, "%Y-%m")) %>% group_by(week) %>% summarise(n=n())
data%>% mutate(week=strftime(date, "%Y-%m")) %>% group_by(week) %>% summarise(n=n()) -> tmp
summary(tmp$n)
sd(tmp$n)
data %>%  mutate(week=strftime(date, "%Y-%m"))
data %>%  mutate(week=strftime(date, "%Y-%m")) %>% select(week="2021-01")
data %>%  mutate(week=strftime(date, "%Y-%m")) %>% filter(week=="2021-01")
View(data %>%  mutate(week=strftime(date, "%Y-%m")) %>% filter(week=="2021-01"))
55/ 30
55/ 20
data %>% mutate(hour=strftime("%h:%M"))
data %>% mutate(hour=strftime("%h:%m"))
data %>% mutate(hour=strftime("%H:%m"))
data %>% mutate(hour=strftime("%H:"))
data %>% mutate(hour=strftime("%H"))
data %>% mutate(hour=strftime(date, "%H"))
data %>% mutate(hour=strftime(date, "%h:%m"))
data %>% mutate(hour=strftime(date, "%H:%m"))
data %>% mutate(hour=strftime(date, "%H:%M"))
data %>% mutate(hour=strftime(date, "%H:%M")) %>% group_by(hour) %>% summarize(n=n())
data %>% mutate(hour=strftime(date, "%H")) %>% group_by(hour) %>% summarize(n=n()) %>%
ggplot(aes(x=hour, y=n)) + geom_bar()
ggplot(aes(x=hour, y=n)) + geom_col()
data %>% mutate(hour=strftime(date, "%H")) %>% group_by(hour) %>% summarize(n=n()) %>% ggplot(aes(x=hour, y=n)) + geom_bar()
data %>% mutate(hour=strftime(date, "%H")) %>% group_by(hour) %>% summarize(n=n()) %>% ggplot(aes(x=hour, y=n)) + geom_col()
ggsave('issue-times.png')
data
data %>% ggplot(aes(x=date,y=org, fill=org)) + geom_histogram()
data %>% ggplot(aes(org)) + geom_histogram()
data %>% ggplot(aes(org)) + geom_histogram(stat="count")
data %>% mutate(j=paste(org, repo, sep="/"))
data %>% mutate(j=paste(org, repo, sep="/")) %>% ggplot(aes(j)) + geom_histogram(stat="count")
commits = read_tsv("commits.tsv")
commits = read_tsv("commits.tsv")
commits %>% mutate(day=as.Date(date)) %>% ggplot(aes(x=day, y=org))
commits %>% mutate(day=as.Date(date)) %>% ggplot(aes(x=day, y=org)) + geom_point()
commits = read_tsv("commits.tsv")
commits %>% mutate(day=as.Date(date)) %>% ggplot(aes(x=day, y=org)) + geom_point()
commits %>% mutate(day=as.Date(date)) %>% group_by(date,day,org,repo) %>% summarise(n=n()) %>% ggplot(aes(x=day, y=org, fill=n)) + geom_point()
commits %>% mutate(day=as.Date(date)) %>% group_by(day,org,repo) %>% summarise(n=n()) %>% ggplot(aes(x=day, y=org, fill=n)) + geom_point()
commits %>% mutate(day=as.Date(date)) %>% group_by(day,org,repo) %>% summarise(n=n()) %>% ggplot(aes(x=day, y=org, fill=n)) + geom_point(fill=n)
commits %>% mutate(day=as.Date(date)) %>% group_by(day,org,repo) %>% summarise(n=n()) %>% ggplot(aes(x=day, y=org, color=n)) + geom_point()
commits %>% mutate(day=as.Date(date)) %>% group_by(day,org,repo) %>% summarise(n=n()) %>% ggplot(aes(x=day, y=org, size=n)) + geom_point()
commits %>% mutate(day=as.Date(date)) %>% group_by(day,org,repo) %>% summarise(n=n()) %>% ggplot(aes(x=day, y=org, size=n)) + geom_bar()
commits %>% mutate(day=as.Date(date)) %>% group_by(day,org,repo) %>% summarise(n=n()) %>% ggplot(aes(x=day, y=org, fill=n)) + geom_bar()
commits %>% mutate(day=as.Date(date)) %>% group_by(day,org,repo) %>% summarise(n=n()) %>% ggplot(aes(x=day, y=org, fill=n)) + geom_col)
commits %>% mutate(day=as.Date(date)) %>% group_by(day,org,repo) %>% summarise(n=n()) %>% ggplot(aes(x=day, y=org, fill=n)) + geom_col()
commits %>% mutate(day=as.Date(date)) %>% group_by(day,org,repo) %>% summarise(n=n()) %>% ggplot(aes(x=day, y=org, fill=n)) + geom_area()
commits %>% mutate(day=as.Date(date)) %>% group_by(day,org,repo) %>% summarise(n=n()) %>% ggplot(aes(x=day, y=org, fill=n)) + geom_density()
commits %>% mutate(day=as.Date(date)) %>% group_by(day,org,repo) %>% summarise(n=n()) %>% ggplot(aes(x=day, fill=org, y=n)) + geom_col()
commits %>% mutate(day=as.Date(date)) %>% group_by(day,org,repo) %>% summarise(n=n()) %>% ggplot(aes(x=day, fill=org, y=n)) + geom_density()
commits %>% mutate(day=as.Date(date)) %>% group_by(day,org,repo) %>% summarise(n=n()) %>% ggplot(aes(x=day, fill=org, y=n)) + geom_col() + theme(legend.position="none")
commits %>% mutate(day=as.Date(date)) %>% group_by(day,org,repo) %>% summarise(n=n()) %>% ggplot(aes(x=day, fill=org, y=n)) + geom_area() + theme(legend.position="none")
commits %>% mutate(day=as.Date(date)) %>% group_by(day,org,repo) %>% summarise(n=n()) %>% ggplot(aes(x=day, fill=org, y=n)) + geom_bar() + theme(legend.position="none")
commits %>% mutate(day=as.Date(date)) %>% group_by(day,org,repo) %>% summarise(n=n()) %>% ggplot(aes(x=day, fill=org, y=n)) + geom_col() + theme(legend.position="none")
commits %>% mutate(day=as.Date(date)) %>% group_by(month = floor_date(date, unit = "month"))
library(lubridate)
commits %>% mutate(day=as.Date(date)) %>% group_by(month = floor_date(date, unit = "month"))
commits %>% mutate(day=as.Date(date)) %>% group_by(month = floor_date(date, unit = "week"))
commits %>% mutate(day=as.Date(date)) %>% group_by(month = floor_date(date, unit = "week"), org, repo)
commits %>% group_by(week = floor_date(date, unit = "week"), org, repo) %>% summarise(n=n())
commits %>% group_by(week = floor_date(date, unit = "week"), org, repo) %>% summarise(n=n()) %>% ggplot(aes(x=week, fill=org, y=n))
commits %>% group_by(week = floor_date(date, unit = "week"), org, repo) %>% summarise(n=n()) %>% ggplot(aes(x=week, fill=org, y=n)) + geom_col()
commits %>% group_by(week = floor_date(date, unit = "week"), org, repo) %>% summarise(n=n()) %>% ggplot(aes(x=week, fill=org, y=n)) + geom_col() + theme(legend.position="none")
commits %>% group_by(week = floor_date(date, unit = "month"), org, repo) %>% summarise(n=n()) %>% ggplot(aes(x=week, fill=org, y=n)) + geom_col() + theme(legend.position="none")
commits %>% group_by(week = floor_date(date, unit = "month"), org, repo) %>% summarise(n=n()) %>% ggplot(aes(x=week, fill=org, y=n)) + geom_area() + theme(legend.position="none")
commits %>% group_by(week = floor_date(date, unit = "month"), org, repo) %>% summarise(n=n()) %>% ggplot(aes(x=week, fill=org, y=n)) + geom_col() + theme(legend.position="none")
commits %>% group_by(week = floor_date(date, unit = "month"), org, repo) %>% summarise(n=n()) %>% ggplot(aes(x=week, fill=org, y=n)) + geom_line() + theme(legend.position="none")
commits %>% group_by(week = floor_date(date, unit = "month"), org, repo) %>% summarise(n=n()) %>% ggplot(aes(x=week, color=org, y=n)) + geom_line() + theme(legend.position="none")
commits %>% group_by(week = floor_date(date, unit = "month"), org, repo) %>% summarise(n=n()) %>% ggplot(aes(x=week, fill=org, y=n)) + geom_col() + theme(legend.position="none")
commits %>% group_by(week = floor_date(date, unit = "month"), org, repo) %>% summarise(n=n()) %>% ggplot(aes(x=week, fill=org, y=n)) + geom_col() + theme(legend.position="none") + facet_grid(org)
commits %>% group_by(week = floor_date(date, unit = "month"), org, repo) %>% summarise(n=n()) %>% ggplot(aes(x=week, fill=org, y=n))+ facet_grid(org) + geom_col() + theme(legend.position="none")
commits %>% group_by(week = floor_date(date, unit = "month"), org, repo) %>% summarise(n=n()) %>% ggplot(aes(x=week, fill=org, y=n)) + geom_col() + theme(legend.position="none") + facet_grid(~org)
commits %>% group_by(week = floor_date(date, unit = "month"), org, repo) %>% summarise(n=n()) %>% ggplot(aes(x=week, fill=org, y=n)) + geom_col() + theme(legend.position="none") + facet_wrap(~org)
commits %>% group_by(week = floor_date(date, unit = "year"), org, repo) %>% summarise(n=n()) %>% filter(n<3)
commits %>% group_by(week = floor_date(date, unit = "year"), org, repo) %>% summarise(n=n()) %>% filter(n<10)
minimal = commits %>% group_by(week = floor_date(date, unit = "year"), org, repo) %>% summarise(n=n()) %>% filter(n<5) %>% mutate(or=paste(org, repo, sep="/"))
minimal
commits %>% mutate(or=paste(org, repo,sep="/") %>% filter(!(or %in% minimal$or)) %>% group_by(week = floor_date(date, unit = "month"), org, repo) %>% summarise(n=n()) %>% ggplot(aes(x=week, fill=org, y=n)) + geom_col() + theme(legend.position="none") + facet_wrap(~org)
)
commits %>% mutate(or=paste(org, repo,sep="/") %>% filter(!(or %in% minimal$or))
)
commits %>% mutate(or=paste(org, repo,sep="/")) %>% filter(!(or %in% minimal$or))
commits %>% mutate(or=paste(org, repo,sep="/")) %>% filter(!(or %in% minimal$or)) %>% group_by(week = floor_date(date, unit = "month"), org, repo) %>% summarise(n=n()) %>% ggplot(aes(x=week, fill=org, y=n)) + geom_col() + theme(legend.position="none") + facet_wrap(~org)
minimal = commits %>% group_by(week = floor_date(date, unit = "year"), org, repo) %>% summarise(n=n()) %>% filter(n<10) %>% mutate(or=paste(org, repo, sep="/"))
commits %>% mutate(or=paste(org, repo,sep="/")) %>% filter(!(or %in% minimal$or)) %>% group_by(week = floor_date(date, unit = "month"), org, repo) %>% summarise(n=n()) %>% ggplot(aes(x=week, fill=org, y=n)) + geom_col() + theme(legend.position="none") + facet_wrap(~org)
commits %>% mutate(or=paste(org, repo,sep="/")) %>% filter(!(or %in% minimal$or)) %>% group_by(week = floor_date(date, unit = "month"), org, repo) %>% summarise(n=n()) %>% ggplot(aes(x=week, fill=repo, y=n)) + geom_col() + theme(legend.position="none") + facet_wrap(~org)
ggsave("orgs-min-10-in-a-year.png")
commits %>% filter(org=="galaxyproject") %>% group_by(week = floor_date(date, unit = "month"), org, repo) %>% summarise(n=n()) %>% ggplot(aes(x=week, fill=org, y=n)) + geom_col() + theme(legend.position="none") + facet_wrap(~org)
commits %>% filter(org=="galaxyproject") %>% group_by(week = floor_date(date, unit = "month"), org, repo) %>% summarise(n=n()) %>% ggplot(aes(x=week, fill=repo, y=n)) + geom_col() + theme(legend.position="none")
commits %>% filter(org=="galaxyproject") %>% group_by(week = floor_date(date, unit = "month"), org, repo) %>% summarise(n=n()) %>% ggplot(aes(x=week, fill=repo, y=n)) + geom_col()
commits %>% filter(org=="galaxyproject") %>% group_by(week = floor_date(date, unit = "month"), org, repo) %>% summarise(n=n()) %>% ggplot(aes(x=week, fill=repo, y=n)) + geom_col()
commits %>% filter(org=="galaxyproject") %>% group_by(week = floor_date(date, unit = "month"), org, repo) %>% summarise(n=n()) %>% ggplot(aes(x=week, fill=repo, y=n)) + geom_col() + facet_wrap(repo)
commits %>% filter(org=="galaxyproject") %>% group_by(week = floor_date(date, unit = "month"), org, repo) %>% summarise(n=n()) %>% ggplot(aes(x=week, fill=repo, y=n)) + geom_col() + facet_wrap(~repo)
commits %>% filter(org=="galaxyproject") %>% group_by(week = floor_date(date, unit = "month"), org, repo) %>% summarise(n=n()) %>% ggplot(aes(x=week, fill=repo, y=n)) + geom_col() + facet_wrap(~repo) + scale_x_log10()
commits %>% filter(org=="galaxyproject") %>% group_by(week = floor_date(date, unit = "month"), org, repo) %>% summarise(n=n()) %>% ggplot(aes(x=week, fill=repo, y=n)) + geom_col() + facet_wrap(~repo) + scale_y_log10()
ggsave("galaxy-commits.png")
commits = read_tsv("commits.tsv")
commits %>% filter(org=="galaxyproject") %>% group_by(week = floor_date(date, unit = "month"), org, repo) %>% summarise(n=n()) %>% ggplot(aes(x=week, fill=repo, y=n)) + geom_col() + facet_wrap(~repo) + scale_y_log10()
commits %>% filter(org=="galaxyproject") %>% mutate(repo=gsub("ansible-.*", "ansible-*", repo)) %>% group_by(week = floor_date(date, unit = "month"), org, repo) %>% summarise(n=n()) %>% ggplot(aes(x=week, fill=repo, y=n)) + geom_col() + facet_wrap(~repo) + scale_y_log10()
commits %>% filter(org=="galaxyproject") %>% mutate(repo=gsub("ansible-.*", "ansible-*", repo)) %>% group_by(week = floor_date(date, unit = "month"), org, repo) %>% summarise(n=n()) %>% ggplot(aes(x=week, fill=repo, y=n)) + geom_col() + facet_wrap(~repo) + scale_y_log10() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
ggsave("galaxy2.png")
commits %>% group_by(week = floor_date(date, unit = "month"), org, repo) %>% summarise(n=n()) %>% ggplot(aes(x=week, y=n)) + geom_col() + facet_wrap(~org) + scale_y_log10() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
minimal = commits %>% group_by(week = floor_date(date, unit = "year"), org, repo) %>% summarise(n=n()) %>% filter(n<10)
minimal = commits %>% group_by(week = floor_date(date, unit = "year"), org) %>% summarise(n=n()) %>% filter(n<10)
minimal
minimal = commits %>% group_by(org) %>% summarise(n=n()) %>% filter(n<10)
minimal
commits %>% filter(!(org %in% minimal$org)) %>% group_by(week = floor_date(date, unit = "month"), org, repo) %>% summarise(n=n()) %>% ggplot(aes(x=week, y=n)) + geom_col() + facet_wrap(~org) + scale_y_log10() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
minimal = commits %>% group_by(org) %>% summarise(n=n()) %>% filter(n<30)
commits %>% filter(!(org %in% minimal$org)) %>% group_by(week = floor_date(date, unit = "month"), org, repo) %>% summarise(n=n()) %>% ggplot(aes(x=week, y=n)) + geom_col() + facet_wrap(~org) + scale_y_log10() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
commits %>% filter(!(org %in% minimal$org)) %>% group_by(week = floor_date(date, unit = "month"), org, repo) %>% summarise(n=n()) %>% ggplot(aes(x=week, y=n)) + geom_col() + facet_wrap(~org) + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
ggsave("commits-all.png")
commits %>% filter(!(org %in% minimal$org)) %>% group_by(week = floor_date(date, unit = "month"), org, repo) %>% summarise(n=n()) %>% ggplot(aes(x=week, y=n)) + geom_col() + facet_wrap(~org) + scale_y_log10() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
commits %>% filter(!(org %in% minimal$org)) %>% group_by(week = floor_date(date, unit = "month"), org, repo) %>% summarise(n=n()) %>% ggplot(aes(x=week, y=n, fill=repo)) + geom_col() + facet_wrap(~org) + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
commits %>% filter(!(org %in% minimal$org)) %>% group_by(week = floor_date(date, unit = "month"), org, repo) %>% summarise(n=n()) %>% ggplot(aes(x=week, y=n, fill=repo)) + geom_col() + facet_wrap(~org) + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1), legend.position="none")
savehistory("commits.R")
