title: "Galaxy Training: A powerful platform for teaching!"
doi: 
prompts:
- "Galaxy Training: A powerful platform for teaching!, magic and computers and biology, ink, white background, red and black minimalise"
final: hexylena_Galaxy_Training_A_powerful_platform_for_teaching_magi_9e21b0d1-cdb4-474b-9181-832d0c821232.png
