title: "Apollo: Democratizing genome annotation."
doi: 10.1371/journal.pcbi.1006790
prompts:
- "Apollo: democratising genome annotation, occult, ink, white background, red and black minimalist"
- "Apollo: democratising genome annotation, ink, white background, red and black minimalist"
- "lunar moon geome, apollo missions and democracy, genome annotation,occult, ink, white background, red and black minimalist"
final: hexylena_lunar_moon_geome_apollo_missions_and_democracy_genome_e29f9b3d-88a2-47f0-b261-3bf2b9715675.png
