title: (Non Chapter) Miscellaneous other images
doi:
prompts:
- a female doctor mage scientist, occult, ink, white background, red and black minimalist
- a female doctor, occult, ink, white background, red and black minimalist
- strands of DNA double helix, occult bioinformatics, ink, white background, red and black minimalist
- cancer, occult bioinformatics, ink, white background, red and black minimalist
- cancerous cell, cancer spreading, occult bioinformatics, ink, white background, red and black minimalist
- computer DNA summoning circle, witches and scientists, occult ink white background red and black minimalist
- digital witch in the server room, ink, white background black and red minimalist, 1s 0s binary
final:
