title: (Non Chapter) Miscellaneous other images
doi:
prompts:
- a female doctor mage scientist, occult, ink, white background, red and black minimalist
- a female doctor, occult, ink, white background, red and black minimalist
- strands of DNA double helix, occult bioinformatics, ink, white background, red and black minimalist
- cancer, occult bioinformatics, ink, white background, red and black minimalist
- cancerous cell, cancer spreading, occult bioinformatics, ink, white background, red and black minimalist
- computer DNA summoning circle, witches and scientists, occult ink white background red and black minimalist
- digital witch in the server room, ink, white background black and red minimalist, 1s 0s binary
- witch in the occult server room, computers and magic, ink, red background, black and white minimalist
- white hat witch in the occult server room, computers and magic, ink, red background, black and white minimalist
- witch in the server room, broom, digital binary, glitches, ink, red background, black and white minimalist
- witch in the server room, ink, red background, black and white minimalist
- witch in the server room, red black and white--niji

final:
