montage.png: platform-front.png training-front.png cancer-front.png annotation-front.png platform-back.png training-back.png cancer-back.png annotation-back.png
	montage -resize 50% platform-front.png training-front.png cancer-front.png annotation-front.png platform-back.png training-back.png cancer-back.png annotation-back.png -geometry +0+0 montage.png
