title: "Planemo: a command-line toolkit for developing, deploying, and executing scientific data analyses"
doi: 10.1101/2022.03.13.483965
prompts:
- "Planemo (astronomy), a command-line toolkit for developing, deploying, and executing scientific data analyses, workflows and testing, ink, white background, red and black minimalist"
- "Planemo: a command-line toolkit for developing, deploying, and executing scientific data analyses, ink, white background, red and black minimalist"
final: hexylena_Planemo_astronomy_a_command-line_toolkit_for_developi_4b6caa71-9251-4dfd-a9ae-2d0e28b7114f.png
