title: "Tripal v3: an ontology-based toolkit for construction of FAIR biological community databases"
doi: 10.1093/database/baz077
prompt: "Tripal v3: an ontology-based toolkit for construction of FAIR biological community databases, occult bioinformatics, ink, white background, red and black minimalist"
final: hexylena_Tripal_v3_an_ontology-based_toolkit_for_construction__69d9c157-0e96-4614-b15d-0c4b6d9dbc35.png
