title: "Training Infrastructure as a Service"
doi: 
prompts:
- teaching and education infrastructure as a service, ink, white background, black and red minamalist
- training and education as a service, ink, white background, black and red minamalist
- training infrastructure as a service, ink, white background, black and red minamalist
final: hexylena_training_and_education_as_a_service_ink_white_backgro_7dfa60b3-3431-4f26-a53a-dd4204a0f164.png
